[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    adafruit/MAX6675 library@^1.1.0
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
